# Libraries and environment

In [ ]:
!pip install selenium
!pip install chrono24
!pip install gower
!pip install bs4 -U

#from sklearn.ensemble import IsolationForest
#from sklearn.neighbors import LocalOutlierFactor
#import chrono24

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
import gower
import sys
import cv2
from warnings import warn
import kmodes
import pandas as pd
import requests
import pickle
from requests import get
import shutil
from bs4 import BeautifulSoup
import re
import json
import time
import xml.etree.ElementTree as ET
import logging
from tqdm import tqdm
from lxml import html
from time import sleep
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MultiLabelBinarizer
from kmodes.kprototypes import KPrototypes
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline
logging.basicConfig(filename='chrono24_listing_download.log', level=logging.DEBUG, filemode='a')
SCRNUM=4
MULTI=False
!pip show selenium

!wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
!tar xvfz geckodriver-v0.19.1-linux64.tar.gz
!mv geckodriver ~/.local/bin

from selenium import webdriver
from selenium.webdriver import FirefoxOptions
from selenium.webdriver.common.by import By
opts = FirefoxOptions()
opts.add_argument("--headless")
browser = webdriver.Firefox(options=opts)

url='https://calibercorner.com/shop/'

session = requests.Session()
# send a get request to the server
response = session.get(url)
# print the response dictionary
cookies=session.cookies.get_dict()
print(session.cookies.get_dict())
BRND='Omega'
response = get(url)
if response.status_code != 200:
     warn('Request: {}; Status code: {}'.format(requests, response.status_code))

Requirement already satisfied: selenium in /opt/conda/lib/python3.10/site-packages (4.22.0)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.26.18)
Requirement already satisfied: trio~=0.17 in /opt/conda/lib/python3.10/site-packages (from selenium) (0.25.1)
Requirement already satisfied: trio-websocket~=0.9 in /opt/conda/lib/python3.10/site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /opt/conda/lib/python3.10/site-packages (from selenium) (2024.2.2)
Requirement already satisfied: typing_extensions>=4.9.0 in /opt/conda/lib/python3.10/site-packages (from selenium) (4.9.0)
Requirement already satisfied: websocket-client>=1.8.0 in /opt/conda/lib/python3.10/site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /opt/conda/lib/python3.10/site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in /opt/conda/lib/python3.10/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /opt/conda/lib/python3.10/site-packages (from trio~=0.17->selenium) (3.6)
Requirement already satisfied: outcome in /opt/conda/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /opt/conda/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: exceptiongroup in /opt/conda/lib/python3.10/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in /opt/conda/lib/python3.10/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /opt/conda/lib/python3.10/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /opt/conda/lib/python3.10/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Requirement already satisfied: chrono24 in /opt/conda/lib/python3.10/site-packages (0.2.10)
Requirement already satisfied: beautifulsoup4>=4.11.0 in /opt/conda/lib/python3.10/site-packages (from chrono24) (4.12.2)
Requirement already satisfied: requests>=2.28.0 in /opt/conda/lib/python3.10/site-packages (from chrono24) (2.32.3)
Requirement already satisfied: tenacity>=8.2.0 in /opt/conda/lib/python3.10/site-packages (from chrono24) (8.2.3)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.10/site-packages (from beautifulsoup4>=4.11.0->chrono24) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests>=2.28.0->chrono24) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests>=2.28.0->chrono24) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests>=2.28.0->chrono24) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests>=2.28.0->chrono24) (2024.2.2)
Requirement already satisfied: gower in /opt/conda/lib/python3.10/site-packages (0.1.2)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from gower) (1.26.4)
Requirement already satisfied: scipy in /opt/conda/lib/python3.10/site-packages (from gower) (1.11.4)
Requirement already satisfied: bs4 in /opt/conda/lib/python3.10/site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in /opt/conda/lib/python3.10/site-packages (from bs4) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /opt/conda/lib/python3.10/site-packages (from beautifulsoup4->bs4) (2.5)
Name: selenium
Version: 4.22.0
Summary: Official Python bindings for Selenium WebDriver
Home-page: https://www.selenium.dev
Author:
Author-email:
License: Apache 2.0
Location: /opt/conda/lib/python3.10/site-packages
Requires: certifi, trio, trio-websocket, typing_extensions, urllib3, websocket-client
Required-by:
--2024-06-28 06:14:20--  https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/25354393/e31e4c22-be6f-11e7-9bc7-dedc3490a7fd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240628%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240628T061420Z&X-Amz-Expires=300&X-Amz-Signature=99306afc00a57a8b237cddf2e3f4ba9a40eafe8d613394cc88a0b370d57f9846&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=25354393&response-content-disposition=attachment%3B%20filename%3Dgeckodriver-v0.19.1-linux64.tar.gz&response-content-type=application%2Foctet-stream [following]
--2024-06-28 06:14:21--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/25354393/e31e4c22-be6f-11e7-9bc7-dedc3490a7fd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240628%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240628T061420Z&X-Amz-Expires=300&X-Amz-Signature=99306afc00a57a8b237cddf2e3f4ba9a40eafe8d613394cc88a0b370d57f9846&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=25354393&response-content-disposition=attachment%3B%20filename%3Dgeckodriver-v0.19.1-linux64.tar.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2301226 (2.2M) [application/octet-stream]
Saving to: 'geckodriver-v0.19.1-linux64.tar.gz.3'

geckodriver-v0.19.1 100%[===================>]   2.19M  10.2MB/s    in 0.2s

2024-06-28 06:14:22 (10.2 MB/s) - 'geckodriver-v0.19.1-linux64.tar.gz.3' saved [2301226/2301226]

geckodriver
{}

/tmp/ipykernel_33/4174878480.py:65: UserWarning: Request: <module 'requests' from '/opt/conda/lib/python3.10/site-packages/requests/__init__.py'>; Status code: 403
  warn('Request: {}; Status code: {}'.format(requests, response.status_code))

In [ ]:
import nltk
nltk.download(['punkt', 'stopwords', 'brown', 'gutenberg'])

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package brown to /usr/share/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package gutenberg to /usr/share/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!

True

In [ ]:
table_of_brandsinloops=pd.read_excel('/kaggle/input/table-of-brandsinloops/table_of_brandsinloops.xlsx',index_col=0)
if MULTI:
    lst_brn=list(table_of_brandsinloops[f'brands{SCRNUM}'])
    l=0
    if lst_brn[-1]!='Completed':
      for d in lst_brn:
       if d!='Completed':
         BRND=d
         table_of_brandsinloops.loc[l,f'brands{SCRNUM}']='Completed'
         table_of_brandsinloops.to_excel("table_of_brandsinloops.xlsx")
         break
       l=l+1
    else:
      lst_upd=list(pd.read_excel('/kaggle/input/table-of-brandsinloops/table_of_brands.xlsx',index_col=0)['brands'])
      lst_upd.remove('Rolex')
      table_of_brandsinloops.loc[:,f'brands{SCRNUM}']=lst_upd
      table_of_brandsinloops.to_excel("table_of_brandsinloops.xlsx")
      print('all brands were completed,run script once more')
      sys.exit('exit')
else:
    _=0

BRND=re.sub('& ','',BRND)
BRND=re.sub('ö','',BRND)
BRND=re.sub('è','',BRND)
BRND=re.sub('ü','',BRND)

In [ ]:
pd.options.mode.copy_on_write = True

In [ ]:
######

# Caliber table upload

In [ ]:
caliber_base_new=pd.read_excel('/kaggle/input/caliber-base/caliber_base_new.xlsx',index_col=0)

In [ ]:
caliber_base_new

,caliber_url,caliber_brand,caliber_name,info,Manufacturer/Brand,Caliber Number,Country of Manufacture,Known Models,Jewels,Functions,...,Quickset Date?,Finishing,Casing Diameter,Balance,Hands,Chronometer,textual_caliber,digital_caliber,code_caliber,caliber_stories
0,https://calibercorner.com/arola-caliber-ar-165/,eta,Arola Caliber AR 165,"{'Brand': 'AROLA Alfred Rochat & Fils S.A.', '...",AROLA Alfred Rochat & Fils S.A.,"AR 165, AR165",Switzerland,Unknown,17,"Hours, minutes",...,Unknown,Unknown,Unknown,Glucydur,Unknown,Unknown,Arola AR,165,Arola AR :165,This example of an Arola caliber AR 165 was fo...
1,https://calibercorner.com/ball-caliber-rr1103/,eta,Ball Caliber RR1103,"{'Brand': 'Ball', 'Caliber Number': 'RR1103, R...",Ball,"RR1103, RR1103-C",Switzerland,Engineer II Pioneer,25 or 26 (see below),"Central hours, central minutes, central sweepi...",...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Ball RR,1103,Ball RR:1103,The Ball caliber RR1103 is a Swiss made automa...
2,https://calibercorner.com/breitling-caliber-b17/,eta,Breitling Caliber 17,"{'Brand': 'Breitling', 'Caliber Number': '17, ...",Breitling,"17, B17",Switzerland,SuperOcean 44,25 or 26 (see below),Central hours; central minutes; central sweepi...,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Breitling,17,Breitling :17,The Breitling caliber 17 (sometimes called Bre...
3,https://calibercorner.com/breitling-caliber-32/,eta,Breitling Caliber 32,"{'Brand': 'Breitling', 'Caliber Number': '32, ...",Breitling,"32, B32",Switzerland,Colt GMT,21,GMT,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Breitling,32,Breitling :32,The Breitling caliber 32 is essentially a COSC...
4,https://calibercorner.com/breitling-caliber-49/,eta,Breitling Caliber 49,"{'Brand': 'Breitling', 'Caliber Number': '49, ...",Breitling,"49, B49",Switzerland,"Breitling Galactic 41 (Ref: A49350, B49350, C4...",22,Unknown,...,Yes,Unknown,Unknown,Unknown,Unknown,Unknown,Breitling,49,Breitling :49,The Breitling caliber 49 (you may also see thi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,https://calibercorner.com/eta-caliber-251-262/,longines,ETA Caliber 251.262,"{'Manufacturer': 'ETA', 'Caliber Number': '251...",ETA,251.262,Switzerland,"Tag Heuer Aquaracer Chrono, Certina DS First, ...",27,chronograph,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,ETA,251,ETA :251,The ETA caliber 251.262 is a 27 jewels quartz ...
461,https://calibercorner.com/eta-caliber-955-112/,longines,ETA Caliber 955.112,"{'Manufacturer': 'ETA', 'Caliber Number': '955...",ETA,"955.112, 955112",Switzerland,Tag Heuer Kirium,7,Central hours; central minutes; central second...,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,ETA,955,ETA :955,The ETA caliber 955.112 is part of ETA’s Normf...
462,https://calibercorner.com/eta-caliber-988-432/,longines,ETA Caliber 988.432,"{'Manufacturer': 'ETA', 'Caliber Number': '988...",ETA,"988.432, 988432",Switzerland,Omega,7,chronograph,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,ETA,988,ETA :988,NaN
463,https://calibercorner.com/eta-caliber-955-122/,longines,ETA Caliber 955.122,"{'Manufacturer': 'ETA', 'Caliber Number': '955...",ETA,955.122,Switzerland,Hamilton Khaki 8775,7,chronograph,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,ETA,955,ETA :955,From a WatchFlipr.com post:Also said to replac...
464,https://calibercorner.com/omega-caliber-1260/,longines,Omega Caliber 1260,"{'Brand': 'Omega', 'Caliber Number': '1260', '...",Omega,1260,Switzerland,SBGM031,Unknown,Central hours; central minutes; central second...,...,Unknown,Unknown,Unknown,Unknown,Unknown,Yes,Omega,1260,Omega :1260,Omega caliber 1260 tuning fork movement from a...

In [ ]:
caliber_columns=caliber_base_new.columns[4:-4]

In [ ]:
# caliber info(data) dictionary
caliber_referdic={}
for s in list(caliber_base_new.index):
    caliber_referdic[caliber_base_new.loc[s,'code_caliber']]=caliber_base_new.loc[s,caliber_columns].to_dict()

# Adding caliber data and stories to catalog

In [ ]:
omega_example=pd.read_excel(f'/kaggle/input/omega-exm-caliber/{BRND.lower()}_cataloguev2.xlsx')

In [ ]:
omega_example['caliber_info']=''

In [ ]:
list_qq=[]
list_value=[]
for qq in list(omega_example.index):
 if omega_example.loc[qq,'caliber_info']=='':
  pat=omega_example.loc[qq,'Base caliber']
  for key,value in caliber_referdic.items():
    mask=key.split(':')[-2].split(' ')
    mask.append(key.split(':')[-1])
    if re.search(mask[-3].lower(),pat.lower()):
      if re.search(mask[-2].lower(),pat.lower()):
        if re.search(r'\d+',pat.lower()).group()==mask[-1]:
          if omega_example.loc[qq,'caliber_info']=='':
            list_qq.append(qq)
            list_value.append(value)
 #           print(f'pattern{pat}-mask{mask}-value{value}')
omega_example.loc[list_qq,'caliber_info']=list_value

In [ ]:
omega_example

,Unnamed: 0,Hierarchy_code,refnum,url,Brand,Model,Reference number,Movement,Case material,Bracelet material,...,Quick Set,Rotating Bezel,Screw-Down Crown,Screw-Down Push-Buttons,Skeletonized,Small seconds,Tempered blue hands,World time watch,hodinkee+bezel model description,caliber_info
0,0,Omega/ cal 1012 automatic/1620052/default,1620052,https://www.chrono24.com/omega/1620052--cal101...,Omega,genève,162.0052,Automatic,Gold/Steel,Leather,...,Yes,No,No,No,No,No,No,No,The Seamaster 300 is an authentic interpretati...,
1,1,Omega/ omega/460031/default,460031,https://www.chrono24.com/omega/460031-devil-pr...,Omega,de ville prestige,4600.31,Automatic,Yellow gold,Leather,...,Yes,No,No,No,No,No,No,No,The De Ville Prestige line is among the most u...,"{'Manufacturer/Brand': ' Omega', 'Caliber Numb..."
2,2,Omega/ seamaster/166011/default,166011,https://www.chrono24.com/omega/166011--cal562-...,Omega,seamaster,166.011,Automatic,Steel,Steel,...,No,No,No,No,No,No,No,No,"The Seamaster Aqua Terra collection is, in our...","{'Manufacturer/Brand': 'Omega ', 'Caliber Numb..."
3,3,Omega/ seamaster/229780/default,229780,https://www.chrono24.com/omega/seamaster-profe...,Omega,seamaster diver 300 m,2297.80,Automatic,Titanium,Titanium,...,No,No,No,No,No,No,No,No,Introduced in 2003 in collaboration with famed...,"{'Manufacturer/Brand': 'Omega ', 'Caliber Numb..."
4,4,Omega/ speedmaster/351161/default,351161,https://www.chrono24.com/omega/omega-speedmast...,Omega,speedmaster,3511.61,Automatic,Steel,Steel,...,No,No,No,No,No,No,No,No,The new Chronoscope pays tribute to OMEGA’s pa...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097,2097,Omega/vintage/2709/default,2709,https://www.chrono24.com/omega/omega-seamaster...,Omega,seamaster,2709,Automatic,Rose gold,Leather,...,No,No,No,No,No,No,No,No,"The Seamaster Aqua Terra collection is, in our...",
2098,2098,Omega/デイト cal 562 自動巻き omega オメガ シーマスター 166010...,16601063,https://www.chrono24.com/omega/166010-63--cal5...,Omega,seamaster,166.010-63,Automatic,Steel,Steel,...,No,No,No,No,No,No,No,No,"The Seamaster Aqua Terra collection is, in our...","{'Manufacturer/Brand': 'Omega ', 'Caliber Numb..."
2099,2099,Omega/de ville trésor/2643/default,2643,https://www.chrono24.com/omega/de-ville-tresor...,Omega,de ville trésor,2643,Automatic,Rose gold,Yellow gold,...,No,No,No,No,No,No,No,No,We wouldn't blame you if at first glance you d...,"{'Manufacturer/Brand': 'Omega ', 'Caliber Numb..."
2100,2100,Omega/de ville/1450/default,1450,https://www.chrono24.com/omega/de-ville-18k-sq...,Omega,de ville,1450,Quartz,Gold/Steel,Gold/Steel,...,No,No,No,No,No,No,No,No,While the Speedmaster was originally introduce...,
2101,2101,Omega/seamaster/2603/default,2603,https://www.chrono24.com/omega/seamaster-jumbo...,Omega,seamaster,2603,Manual winding,Steel,Leather,...,No,No,No,No,No,No,No,No,"The Seamaster Aqua Terra collection is, in our...",

In [ ]:
#omega_example[['Base caliber']]

In [ ]:
cal_uniq_num=caliber_base_new.groupby('digital_caliber')['digital_caliber'].count()

In [ ]:
cal_notrep_num=list((pd.DataFrame(cal_uniq_num).rename_axis('index')[pd.DataFrame(cal_uniq_num).rename_axis('index')['digital_caliber']==1]).index)

In [ ]:
cal_notrep_num

[3,
 8,
 12,
 16,
 17,
 18,
 23,
 30,
 32,
 33,
 35,
 37,
 38,
 44,
 45,
 56,
 59,
 60,
 64,
 71,
 72,
 76,
 100,
 120,
 121,
 185,
 210,
 221,
 261,
 263,
 300,
 302,
 400,
 431,
 435,
 500,
 509,
 595,
 619,
 633,
 645,
 688,
 690,
 704,
 705,
 706,
 708,
 712,
 715,
 733,
 735,
 743,
 756,
 762,
 770,
 785,
 800,
 802,
 836,
 860,
 893,
 940,
 956,
 988,
 1019,
 1069,
 1103,
 1137,
 1701,
 1726,
 1847,
 1902,
 1917,
 2001,
 2002,
 2035,
 2050,
 2094,
 2105,
 2115,
 2225,
 2353,
 2390,
 2415,
 2453,
 2500,
 2508,
 2523,
 2525,
 2542,
 2600,
 2601,
 2610,
 2612,
 2671,
 2700,
 2706,
 2806,
 2807,
 2809,
 2824,
 2825,
 2836,
 2842,
 2850,
 2851,
 2870,
 2872,
 2878,
 2894,
 2896,
 2899,
 2906,
 3021,
 3023,
 3120,
 3265,
 3510,
 3520,
 3540,
 3572,
 3621,
 4012,
 4120,
 4280,
 5030,
 5100,
 5130,
 5206,
 5400,
 5402,
 5740,
 5813,
 5833,
 6004,
 6203,
 6325,
 6503,
 6620,
 7001,
 7753,
 8040,
 8136,
 8200,
 8203,
 8204,
 8210,
 8229,
 8285,
 8310,
 9011,
 9075,
 32111]

In [ ]:
list_qq=[]
list_value=[]
for qq in list(omega_example.index):
 if omega_example.loc[qq,'caliber_info']=='':
  pat=str(omega_example.loc[qq,'Caliber/movement'])
  for key,value in caliber_referdic.items():
    mask=key.split(':')[-2].split(' ')
    mask.append(key.split(':')[-1])
    if mask[-2]!='':
      if re.search(mask[-2].lower(),pat.lower()):
       if re.search(r'\d+',pat.lower()):
        if re.search(r'\d+',pat.lower()).group()==mask[-1]:
          if omega_example.loc[qq,'caliber_info']=='':
            list_qq.append(qq)
            list_value.append(value)
 #           print(f'pattern{pat}-mask{mask}-value{value}')
omega_example.loc[list_qq,'caliber_info']=list_value

In [ ]:
list_qq=[]
list_value=[]
for qq in list(omega_example.index):
  if omega_example.loc[qq,'caliber_info']=='':
    pat=str(omega_example.loc[qq,'Caliber/movement'])
 #   print(pat)
    for hh in list(caliber_base_new.index):
      cnu=caliber_base_new.loc[hh,'Caliber Number'].split(',')
      for w in range(0,len(cnu)):
        if re.search(re.sub(r'\W+','',cnu[w]).lower(),re.sub(r'\W+','',pat).lower()):
         if re.sub(r'\W+','',cnu[w]).lower()==re.sub(r'\W+','',pat).lower():
           if omega_example.loc[qq,'caliber_info']=='':
              list_qq.append(qq)
              list_value.append(caliber_base_new.loc[hh,caliber_columns].to_dict())
omega_example.loc[list_qq,'caliber_info']=list_value

In [ ]:
list_qq=[]
list_value=[]
for qq in list(omega_example.index):
    if omega_example.loc[qq,'caliber_info']=='':
        pat=omega_example.loc[qq,'Base caliber']
        for key,value in caliber_referdic.items():
          mask=key.split(':')[-2].split(' ')
          mask.append(key.split(':')[-1])
          if mask[-1] in cal_notrep_num:
            if re.search(r'\d+',pat.lower()).group()==mask[-1]:
              if omega_example.loc[qq,'caliber_info']=='':
                list_qq.append(qq)
                list_value.append(value)
#                print(f'pattern{pat}-mask{mask}-value{value}')
omega_example.loc[list_qq,'caliber_info']=list_value

In [ ]:
omega_example

,Unnamed: 0,Hierarchy_code,refnum,url,Brand,Model,Reference number,Movement,Case material,Bracelet material,...,Quick Set,Rotating Bezel,Screw-Down Crown,Screw-Down Push-Buttons,Skeletonized,Small seconds,Tempered blue hands,World time watch,hodinkee+bezel model description,caliber_info
0,0,Omega/ cal 1012 automatic/1620052/default,1620052,https://www.chrono24.com/omega/1620052--cal101...,Omega,genève,162.0052,Automatic,Gold/Steel,Leather,...,Yes,No,No,No,No,No,No,No,The Seamaster 300 is an authentic interpretati...,
1,1,Omega/ omega/460031/default,460031,https://www.chrono24.com/omega/460031-devil-pr...,Omega,de ville prestige,4600.31,Automatic,Yellow gold,Leather,...,Yes,No,No,No,No,No,No,No,The De Ville Prestige line is among the most u...,"{'Manufacturer/Brand': ' Omega', 'Caliber Numb..."
2,2,Omega/ seamaster/166011/default,166011,https://www.chrono24.com/omega/166011--cal562-...,Omega,seamaster,166.011,Automatic,Steel,Steel,...,No,No,No,No,No,No,No,No,"The Seamaster Aqua Terra collection is, in our...","{'Manufacturer/Brand': 'Omega ', 'Caliber Numb..."
3,3,Omega/ seamaster/229780/default,229780,https://www.chrono24.com/omega/seamaster-profe...,Omega,seamaster diver 300 m,2297.80,Automatic,Titanium,Titanium,...,No,No,No,No,No,No,No,No,Introduced in 2003 in collaboration with famed...,"{'Manufacturer/Brand': 'Omega ', 'Caliber Numb..."
4,4,Omega/ speedmaster/351161/default,351161,https://www.chrono24.com/omega/omega-speedmast...,Omega,speedmaster,3511.61,Automatic,Steel,Steel,...,No,No,No,No,No,No,No,No,The new Chronoscope pays tribute to OMEGA’s pa...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2097,2097,Omega/vintage/2709/default,2709,https://www.chrono24.com/omega/omega-seamaster...,Omega,seamaster,2709,Automatic,Rose gold,Leather,...,No,No,No,No,No,No,No,No,"The Seamaster Aqua Terra collection is, in our...",
2098,2098,Omega/デイト cal 562 自動巻き omega オメガ シーマスター 166010...,16601063,https://www.chrono24.com/omega/166010-63--cal5...,Omega,seamaster,166.010-63,Automatic,Steel,Steel,...,No,No,No,No,No,No,No,No,"The Seamaster Aqua Terra collection is, in our...","{'Manufacturer/Brand': 'Omega ', 'Caliber Numb..."
2099,2099,Omega/de ville trésor/2643/default,2643,https://www.chrono24.com/omega/de-ville-tresor...,Omega,de ville trésor,2643,Automatic,Rose gold,Yellow gold,...,No,No,No,No,No,No,No,No,We wouldn't blame you if at first glance you d...,"{'Manufacturer/Brand': 'Omega ', 'Caliber Numb..."
2100,2100,Omega/de ville/1450/default,1450,https://www.chrono24.com/omega/de-ville-18k-sq...,Omega,de ville,1450,Quartz,Gold/Steel,Gold/Steel,...,No,No,No,No,No,No,No,No,While the Speedmaster was originally introduce...,
2101,2101,Omega/seamaster/2603/default,2603,https://www.chrono24.com/omega/seamaster-jumbo...,Omega,seamaster,2603,Manual winding,Steel,Leather,...,No,No,No,No,No,No,No,No,"The Seamaster Aqua Terra collection is, in our...",

In [ ]:
#caliber story dictionary
caliber_referdicst={}
for s in list(caliber_base_new.index):
    caliber_referdicst[caliber_base_new.loc[s,'code_caliber']]=caliber_base_new.loc[s,'caliber_stories']

In [ ]:
omega_example['caliber_stories']=''

In [ ]:
list_qq=[]
list_value=[]
for qq in list(omega_example.index):
 if omega_example.loc[qq,'caliber_stories']=='':
  pat=omega_example.loc[qq,'Base caliber']
  for key,value in caliber_referdicst.items():
    mask=key.split(':')[-2].split(' ')
    mask.append(key.split(':')[-1])
    if re.search(mask[-3].lower(),pat.lower()):
      if re.search(mask[-2].lower(),pat.lower()):
        if re.search(r'\d+',pat.lower()).group()==mask[-1]:
          if omega_example.loc[qq,'caliber_stories']=='':
            list_qq.append(qq)
            list_value.append(value)
omega_example.loc[list_qq,'caliber_stories']=list_value

In [ ]:
list_qq=[]
list_value=[]
for qq in list(omega_example.index):
 if omega_example.loc[qq,'caliber_stories']=='':
  pat=str(omega_example.loc[qq,'Caliber/movement'])
  for key,value in caliber_referdicst.items():
    mask=key.split(':')[-2].split(' ')
    mask.append(key.split(':')[-1])
    if mask[-2]!='':
      if re.search(mask[-2].lower(),pat.lower()):
       if re.search(r'\d+',pat.lower()):
        if re.search(r'\d+',pat.lower()).group()==mask[-1]:
          if omega_example.loc[qq,'caliber_stories']=='':
            list_qq.append(qq)
            list_value.append(value)
omega_example.loc[list_qq,'caliber_stories']=list_value

In [ ]:
list_qq=[]
list_value=[]
for qq in list(omega_example.index):
  if omega_example.loc[qq,'caliber_stories']=='':
    pat=str(omega_example.loc[qq,'Caliber/movement'])
    for hh in list(caliber_base_new.index):
      cnu=caliber_base_new.loc[hh,'Caliber Number'].split(',')
      for w in range(0,len(cnu)):
        if re.search(re.sub(r'\W+','',cnu[w]).lower(),re.sub(r'\W+','',pat).lower()):
          if re.sub(r'\W+','',cnu[w]).lower()==re.sub(r'\W+','',pat).lower():
            if omega_example.loc[qq,'caliber_stories']=='':
              list_qq.append(qq)
              list_value.append(caliber_base_new.loc[hh,'caliber_stories'])
omega_example.loc[list_qq,'caliber_stories']=list_value

In [ ]:
list_qq=[]
list_value=[]
for qq in list(omega_example.index):
    if omega_example.loc[qq,'caliber_stories']=='':
        pat=omega_example.loc[qq,'Base caliber']
        for key,value in caliber_referdicst.items():
          mask=key.split(':')[-2].split(' ')
          mask.append(key.split(':')[-1])
          if mask[-1] in cal_notrep_num:
            if re.search(r'\d+',pat.lower()).group()==mask[-1]:
              if omega_example.loc[qq,'caliber_stories']=='':
                list_qq.append(qq)
                list_value.append(value)
omega_example.loc[list_qq,'caliber_stories']=list_value

In [ ]:
#omega_example.drop(0,axis=1,inplace=True)
omega_example=omega_example.fillna('Unknown')

# Sub reference number creation

In [ ]:
map_subrefnew=pd.read_excel(f'/kaggle/input/map-subref/map_subrefnew{BRND.lower()}v1.xlsx',dtype={'indexcol': str},index_col=0)

In [ ]:
map_subrefnew_dic=map_subrefnew.drop('name',axis=1).set_index(0).to_dict()['indexcol']

In [ ]:
map_subrefnew_dic

{'Dia_Gold': '01',
 'Dia_Silver': '02',
 'Dia_Blue': '03',
 'Dia_Bordeaux': '04',
 'Dia_White': '05',
 'Dia_Champagne': '06',
 'Dia_Black': '08',
 'Dia_Yellow': '09',
 'Dia_Mother of pearl': '10',
 'Dia_Grey': '11',
 'Dia_Bronze': '12',
 'Dia_Green': '13',
 'Dia_Purple': '14',
 'Dia_Silver (solid)': '15',
 'Dia_Brown': '16',
 'Dia_Red': '17',
 'Dia_Pink': '18',
 'Dia_Gold (solid)': '19',
 'Dia_Orange': '20',
 'Brm_Leather': '01',
 'Brm_Steel': '03',
 'Brm_Titanium': '04',
 'Brm_Calf skin': '05',
 'Brm_Yellow gold': '06',
 'Brm_Crocodile skin': '07',
 'Brm_Textile': '08',
 'Brm_Lizard skin': '09',
 'Brm_Rose gold': '10',
 'Brm_Rubber': '11',
 'Brm_Gold/Steel': '12',
 'Brm_Ceramic': '13',
 'Brm_Silver': '14',
 'Brm_Red gold': '15',
 'Brm_White gold': '16',
 'Brm_Satin': '17',
 'Brm_Ostrich skin': '18',
 'Brm_Snake skin': '19',
 'Brm_Plastic': '20',
 'Brm_Silicon': '21',
 'Brm_Aluminium': '22',
 'Bem_Gold/Steel': '02',
 'Bem_Steel': '03',
 'Bem_Titanium': '04',
 'Bem_Yellow gold': '05',
 'Bem_Rose gold': '06',
 'Bem_Ceramic': '07',
 'Bem_Aluminum': '08',
 'Bem_Red gold': '09',
 'Bem_White gold': '10',
 'Bem_Tungsten': '11',
 'Bem_Silver': '12',
 'Bem_Platinum': '13',
 'Bem_Carbon': '14',
 'Bem_Tantalum': '15',
 'Bem_Palladium': '16',
 'Bem_Plastic': '17',
 'Bem_Bronze': '18',
 'Din_No numerals': '02',
 'Din_Arabic numerals': '03',
 'Din_Roman numerals': '04',
 'Brc_Brown': '02',
 'Brc_Gold': '03',
 'Brc_Blue': '04',
 'Brc_Steel': '05',
 'Brc_Black': '06',
 'Brc_Yellow': '07',
 'Brc_Grey': '08',
 'Brc_Bordeaux': '09',
 'Brc_Green': '10',
 'Brc_Beige': '11',
 'Brc_Red': '12',
 'Brc_Silver': '13',
 'Brc_Gold/Steel': '14',
 'Brc_White': '15',
 'Brc_Pink': '16',
 'Brc_Purple': '17',
 'Brc_Orange': '18',
 'Brc_Bronze': '19',
 'Clm_Gold/Steel': '02',
 'Clm_Aluminum': '03',
 'Clm_Steel': '04',
 'Clm_Yellow gold': '05',
 'Clm_Rose Gold': '06',
 'Clm_Red gold': '07',
 'Clm_Titanium': '08',
 'Clm_Plastic': '09',
 'Clm_White Gold': '10',
 'Clm_Silver': '11',
 'Clm_Platinum': '12',
 'Clm_Bronze': '13',
 'Cla_Buckle': '02',
 'Cla_Fold clasp': '03',
 'Cla_Jewelry clasp': '04',
 'Cla_Double-fold clasp': '05',
 'Cla_Fold clasp, hidden': '06',
 'Cla_No clasp': '07',
 'Cam_Gold/Steel': '02',
 'Cam_Steel': '03',
 'Cam_Yellow gold': '04',
 'Cam_Titanium': '05',
 'Cam_White gold': '06',
 'Cam_Rose gold': '07',
 'Cam_Red gold': '08',
 'Cam_Ceramic': '09',
 'Cam_Platinum': '10',
 'Cam_Bronze': '11',
 'Cam_Silver': '12',
 'Cam_Tungsten': '13',
 'Cam_Carbon': '14',
 'Cam_Aluminum': '15'}

In [ ]:
cllist=['Dial','Bracelet material',
 'Bezel material',
 'Dial numerals',
 'Bracelet color',
 'Clasp material',
 'Clasp','Case material']

In [ ]:
omega_example_sub=omega_example[cllist]

In [ ]:
omega_example_sub_=pd.get_dummies(omega_example_sub, prefix=['Dia','Brm', 'Bem','Din','Brc','Clm','Cla','Cam'])

In [ ]:
sub_refrea=[]
for ww in list(omega_example_sub_.index):
    sub_refv=[]
    sub_refva=''
    for vv in list(omega_example_sub_.columns):
        if omega_example_sub_.loc[ww,vv]==True:
            sub_refv.append(map_subrefnew_dic[vv])
    sub_refva=''.join(sub_refv)
    sub_refrea.append(sub_refva)

In [ ]:
omega_example['sub_ref']=sub_refrea

In [ ]:
omega_example.columns

Index(['Unnamed: 0', 'Hierarchy_code', 'refnum', 'url', 'Brand', 'Model',
       'Reference number', 'Movement', 'Case material', 'Bracelet material',
       'Year of production', 'Condition', 'Scope of delivery', 'Gender',
       'Location', 'Availability', 'Caliber/movement', 'Power reserve',
       'Number of jewels', 'Base caliber', 'Frequency', 'Case diameter',
       'Thickness', 'Crystal', 'Dial', 'Water resistance', 'Bezel material',
       'Dial numerals', 'Bracelet length', 'Lug width', 'Clasp',
       'Bracelet color', 'Clasp material', 'Bracelet thickness',
       'Buckle width', 'Complications', 'Description', 'Seller rating',
       'PriceUSDthou', 'Central seconds', 'Chronometer', 'Crown Left',
       'Display back', 'Gemstones and/or diamonds', 'Genevian Seal',
       'Guilloché dial', 'Helium Valve', 'Limited Edition', 'Luminous hands',
       'Luminous indices', 'Luminous numerals', 'Master Chronometer',
       'Only Original Parts', 'PVD/DLC coating', 'Power Reserve Display',
       'Quick Set', 'Rotating Bezel', 'Screw-Down Crown',
       'Screw-Down Push-Buttons', 'Skeletonized', 'Small seconds',
       'Tempered blue hands', 'World time watch',
       'hodinkee+bezel model description', 'caliber_info', 'caliber_stories',
       'sub_ref'],
      dtype='object')

# Data and features normalization

In [ ]:

#refnum_list_calibdrop=list(pd.read_csv(f'/kaggle/input/refnum_list_calibdrop/refnum_list_calibdrop{BRND.lower()}v1.csv',index_col=0)['0'])
#for tt in list(omega_example.index):
# if omega_example.loc[tt,'refnum'] in refnum_list_calibdrop:
#    omega_example.drop([tt],axis=0,inplace=True)
       
omega_example.rename(columns={"Frequency": "Frequency from model"},inplace=True)

omega_example.rename(columns={"Caliber/movement": "Caliber Number1"},inplace=True)

omega_example.rename(columns={"Movement": "Movement1"},inplace=True)

omega_example.rename(columns={"Number of jewels": "Number of jewels1"},inplace=True)

omega_example.rename(columns={"Power reserve": "Power reserve1"},inplace=True)

omega_example.rename(columns={"Base caliber": "Base caliber1"},inplace=True)

omega_example=pd.concat([omega_example,omega_example['caliber_info'].apply(pd.Series)],axis=1)

omega_example.drop(0,axis=1,inplace=True)
omega_example.fillna('Unknown',inplace=True)

omega_example.rename(columns={"Frequency": "Frequency from caliber"},inplace=True)

omega_example.rename(columns={"Caliber Number": "Caliber Number2"},inplace=True)    

omega_example.rename(columns={"Movement Type": "Movement2"},inplace=True)

omega_example.rename(columns={"Jewels": "Number of jewels2"},inplace=True)

omega_example.rename(columns={"Power Reserve": "Power reserve2"},inplace=True)

omega_example.rename(columns={"Base Caliber": "Base caliber2"},inplace=True)

for nn in ["Base caliber2","Movement2","Number of jewels2","Power reserve2","Caliber Number2"]:
    for mm in list(omega_example.index):
        if omega_example.loc[mm,nn]=='Unknown':
            omega_example.loc[mm,nn]=omega_example.loc[mm,(nn[0:-1]+'1')]

for tt in list(omega_example.index):
    b=omega_example.loc[tt,'Caliber Number2'].split(',')
    bb=[]
    for x in b:
      if re.search(r'\d+',x): 
         bb.append(re.search(r'\d+',x).group())
    if re.search(r'\d+',omega_example.loc[tt,'Caliber Number1']):
      if re.search(r'\d+',omega_example.loc[tt,'Caliber Number1']).group() not in bb:
            omega_example.loc[tt,'Caliber Number2']=omega_example.loc[tt,'Caliber Number1']
            
omega_example.drop(["Base caliber1","Movement1","Number of jewels1","Power reserve1","Caliber Number1"],axis=1,inplace=True)

omega_example.drop(["Gender","Location"],axis=1,inplace=True)

omega_example.rename(columns={"Movement2":"Movement","Number of jewels2":"Number of jewels","Power reserve2":"Power reserve","Base caliber2":"Base caliber","Caliber Number2":"Caliber Number"},inplace=True)

omega_example

omega_example[omega_example.caliber_info=='']

,Unnamed: 0,Hierarchy_code,refnum,url,Brand,Model,Reference number,Case material,Bracelet material,Year of production,...,Rotor Style,Anti-Shock System,Escapement,Balance Spring,Quickset Date?,Finishing,Casing Diameter,Balance,Hands,Chronometer
0,0,Omega/ cal 1012 automatic/1620052/default,1620052,https://www.chrono24.com/omega/1620052--cal101...,Omega,genève,162.0052,Gold/Steel,Leather,1970,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,4,Omega/ speedmaster/351161/default,351161,https://www.chrono24.com/omega/omega-speedmast...,Omega,speedmaster,3511.61,Steel,Steel,1997,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
6,6,Omega/2402 1/24021/default,24021,https://www.chrono24.com/omega/seamaster--id30...,Omega,seamaster,2402-1,Steel,Leather,1952,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
7,7,Omega/428 55 26 60 04 001/42855266004001/default,42855266004001,https://www.chrono24.com/omega/de-ville-mini-t...,Omega,de ville trésor,428.55.26.60.04.001,Yellow gold,Yellow gold,2023,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
8,8,Omega/428 57 26 60 04 002/42857266004002/default,42857266004002,https://www.chrono24.com/omega/de-ville-mini-t...,Omega,de ville trésor,428.57.26.60.04.002,Yellow gold,Textile,2023,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2095,2095,Omega/vintage/1660124/default,1660124,https://www.chrono24.com/omega/geneve--id31132...,Omega,genève,166 0124,Steel,Steel,1970,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2096,2096,Omega/vintage/250360/default,250360,https://www.chrono24.com/omega/seamaster-aqua-...,Omega,seamaster aqua terra,2503.60,Steel,Steel,2006,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2097,2097,Omega/vintage/2709/default,2709,https://www.chrono24.com/omega/omega-seamaster...,Omega,seamaster,2709,Rose gold,Leather,1954,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2100,2100,Omega/de ville/1450/default,1450,https://www.chrono24.com/omega/de-ville-18k-sq...,Omega,de ville,1450,Gold/Steel,Gold/Steel,1989,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2101,2101,Omega/seamaster/2603/default,2603,https://www.chrono24.com/omega/seamaster-jumbo...,Omega,seamaster,2603,Steel,Leather,1955,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [ ]:
omega_example.rename(columns={"Frequency from model": "Frequency"},inplace=True)

In [ ]:
ms='Unknown'
listfreq=['32768','32,768','32.768']
for xx in list(omega_example.index):
  bridge1=omega_example.loc[xx,'Frequency from caliber']
  if re.search(r'[^a-zA-Z]+',bridge1):
    if re.search('hz',bridge1.lower()):
      if re.search('khz',bridge1.lower()):
        if re.search(r'[^a-zA-Z]+',bridge1).group() in listfreq:
          ms=re.sub(r'\W+','',bridge1)
        else:
            if re.search(r'\d+',re.sub(r'\W+','',bridge1)):
               ms=str(float(re.search(r'\d+',re.sub(r'\W+','',bridge1)).group())*1000)+' Hz'
            else:
                ms='Unknown'
      else:
        ms=re.sub(r'\W+','',bridge1)
    else:
        ms=re.sub(r'\W+','',bridge1)
  else:
    ms='Unknown'
  omega_example.loc[xx,'Frequency from caliber']=ms

In [ ]:
for zz in list(omega_example.index):
  if (omega_example.loc[zz,'Movement']).lower()=='quartz':
    bridge2=omega_example.loc[zz,'Frequency from caliber']
    omega_example.loc[zz,'Frequency']=bridge2

In [ ]:
ms='Unknown'
exclnum=['2.75','3.5']
for yy in list(omega_example.index):
  bridge3=omega_example.loc[yy,'Frequency']
  if re.search('hz',bridge3.lower()):
    if re.search(r'[^a-zA-Z]+',bridge3):
     ms=re.search(r'[^a-zA-Z]+',bridge3).group()
    else:
      ms='Unknown'
  elif re.search('a/h',bridge3.lower()):
    if re.search(r'[^a-zA-Z]+',bridge3):
      if re.search(r'\d+',re.sub(r'\W+','',bridge3)):
        ms=str(round(float(re.search(r'\d+',re.sub(r'\W+','',bridge3)).group())/7200,2))
        if ms in exclnum:
             _=0
        else:
             ms=str(round(float(ms),0))
      else:
        ms='Unknown'
    else:
        ms='Unknown'
  else:
    if re.search(r'[^a-zA-Z]+',bridge3):
      ms='Unknown'
    else:
        ms='Unknown'
  omega_example.loc[yy,'Frequency']=ms

In [ ]:
for hh in list(omega_example.index):
   bridge4=omega_example.loc[hh,'Frequency']
   if re.search(r'[^a-zA-Z]+',bridge4):
     if re.search(r'[^a-zA-Z]+',re.sub(r'\W+','',bridge4)).group()=='25200':
        omega_example.loc[hh,'Frequency']='3.5'
     elif re.search(r'[^a-zA-Z]+',re.sub(r'\W+','',bridge4)).group()=='28800':
        omega_example.loc[hh,'Frequency']='4'

In [ ]:
#for jj in list(omega_example.index):
#   bridge5=omega_example.loc[jj,'Frequency']
#   if re.search(',',bridge5):
#       print(bridge5)
#       omega_example.drop(jj,axis=0,inplace=True)

In [ ]:
for uu in list(omega_example.index):
   bridge6=omega_example.loc[uu,'Frequency']
   if bridge6[-2:]=='.0':
     omega_example.loc[uu,'Frequency']=bridge6[:-2]

In [ ]:
for zz in list(omega_example.index):
  if (omega_example.loc[zz,'Movement']).lower()=='quartz':
    bridge7=omega_example.loc[zz,'Frequency']
    if bridge7=='Unknown':
       omega_example.loc[zz,'Frequency']='32768'

In [ ]:
omega_example['Frequency']=omega_example['Frequency'].astype('string')

In [ ]:
omega_example['sub_ref']=omega_example['sub_ref'].astype('string')

In [ ]:
omega_example['Country of manufacture for the watch']=''

In [ ]:
omega_example['Country of manufacture for the watch']='Switzerland'

In [ ]:
extn=list(omega_example.columns)[(list(omega_example.columns).index('PriceUSDthou')+1):list(omega_example.columns).index('hodinkee+bezel model description')]

In [ ]:
try:
  omega_example=omega_example[['Hierarchy_code', 'refnum','sub_ref','Brand', 'Model','Country of manufacture for the watch',
       'Case material','Bracelet material','Bezel material', 'Clasp material', 'Clasp','Bracelet color',
       'Dial', 'Dial numerals','Crystal','Number of jewels','Power reserve', 'Movement',
       'Case diameter', 'Water resistance','Thickness','Lug width']+extn+['Complications','Manufacturer/Brand','Base caliber', 'Caliber Number','Country of Manufacture','Frequency','In-House',
       'Hacking Seconds?','hodinkee+bezel model description','caliber_stories']]
except:
    print('no columns,order of columns is not correct')

In [ ]:
omega_example.rename(columns={"sub_ref": "sub_ref(index order: Dial,Bracelet material,Bezel material,Dial numerals,Bracelet color,Clasp material,Clasp,Case material)"},inplace=True)

In [ ]:
k=0
indlist=list(omega_example.columns)
ind_repcolumns=[]
list_repcolumns=[]
for y in list(omega_example.columns):
  try:
   if y==list(omega_example.columns)[k+1]:
     ind_repcolumns.append(k+1)
   k=k+1
  except:
    print('end of list')
for z in ind_repcolumns:
    if list(omega_example.columns)[z] in ['In-House','Hacking Seconds?']:
        indlist[(z-1)]=list(omega_example.columns)[z]+'rep'
        list_repcolumns.append(indlist[(z-1)])
    else:
        indlist[z]=list(omega_example.columns)[z]+'rep'
        list_repcolumns.append(indlist[z])
#pd.Index(indlist)
omega_example=pd.DataFrame(np.array(omega_example),columns=pd.Index(indlist))
omega_example.drop(list_repcolumns,axis=1,inplace=True)
print(f'deleted:{list_repcolumns}')

end of list
deleted:['Thicknessrep', 'Chronometerrep']

In [ ]:
try:
  omega_example['Power reserve']=[re.search(r'\d+',y).group() if re.search(r'\d+',y) else '0' for y in list(omega_example['Power reserve'])]
except:
    print('no column')

In [ ]:
omega_example['Number of jewels']=omega_example['Number of jewels'].astype('string')

In [ ]:
try:
   omega_example['Case diameter']=[re.sub(r'[A-Za-z]+','',y) for y in list(omega_example['Case diameter'])]
except:
   print('no column')

In [ ]:
try:
   omega_example['Thickness']=[re.sub(r'[A-Za-z]+','',y) for y in list(omega_example['Thickness'])]
except:
   print('no column')

In [ ]:
try:
   omega_example['Lug width']=[re.sub(r'\D+','',y) for y in list(omega_example['Lug width'])]
except:
   print('no column')

In [ ]:
omega_example['Thickness']=omega_example['Thickness'].astype('string')
omega_example['Lug width']=omega_example['Lug width'].astype('string')
try:
  omega_example['Thickness']=[y if float(re.search(r'\d+',y).group())<100  else 'Unknown' for y in list(omega_example['Thickness'])]
except:
   print('no column')
try:
  omega_example['Lug width']=[y if float(re.search(r'\d+',y).group())<100  else 'Unknown' for y in list(omega_example['Lug width'])]
except:
   print('no column')

In [ ]:
try:
   omega_example['Water resistance']=[re.sub(r'\D+','',y) for y in list(omega_example['Water resistance'])]
except:
   print('no column')

In [ ]:
for bb in list(omega_example.index):
  hc_old=omega_example.loc[bb,'Hierarchy_code']
  if len(hc_old.split('/')[1].split(' '))>2:
    hc_new= hc_old.split('/')[0]+'/'+omega_example.loc[bb,'Model']+'/'+hc_old.split('/')[2]+'/'+hc_old.split('/')[3]
    omega_example.loc[bb,'Hierarchy_code']=hc_new

In [ ]:
if BRND=='Cartier':
   omega_example['Manufacturer/Brand']=[re.sub(r'\(.*?\)','',y) for y in list(omega_example['Manufacturer/Brand'])]

In [ ]:
try:
  for tt in list(omega_example.index):
    if not re.search(omega_example.loc[tt,'Brand'].lower(),omega_example.loc[tt,'Base caliber'].lower()):
      omega_example.loc[tt,'In-House']='No'
except:
    print('error')

In [ ]:
for hh in list(omega_example.index):
  if omega_example.loc[hh,'Base caliber'].isdigit():
    omega_example.loc[hh,'Base caliber']=omega_example.loc[hh,'Brand']+' '+omega_example.loc[hh,'Caliber Number']

In [ ]:
for hh in list(omega_example.index):
    if omega_example.loc[hh,'Manufacturer/Brand']==' ':
      if re.search(r'[A-Za-z]+',omega_example.loc[hh,'Base caliber']):     
        omega_example.loc[hh,'Manufacturer/Brand']=re.search(r'[A-Za-z]+',omega_example.loc[hh,'Base caliber']).group()
 #       print(omega_example.loc[hh,'Manufacturer/Brand'])

In [ ]:
for hh in list(omega_example.index):
    if re.search('Technically no',omega_example.loc[hh,'In-House']):
        omega_example.loc[hh,'In-House']='No'

In [ ]:
if BRND=='Patek Philippe':
    try:
      omega_example['In-House']='Yes'
    except:
        print('no column')

In [ ]:
listmov=['690','687','057','157']
if BRND=='Cartier':
 for tt in list(omega_example.index):
  if re.search(r'\d+',omega_example.loc[tt,'Base caliber']):
    if re.search(r'\d+',omega_example.loc[tt,'Base caliber']).group() in listmov:
      omega_example.loc[tt,'In-House']='No'

In [ ]:
listmov=['690','687','057','157']
if BRND=='Cartier':
 for tt in list(omega_example.index):
  if re.search(r'\d+',omega_example.loc[tt,'Base caliber']):
    if re.search(r'\d+',omega_example.loc[tt,'Base caliber']).group() in listmov:
       omega_example.loc[tt,'Base caliber']='Piaget '+re.search(r'\d+',omega_example.loc[tt,'Base caliber']).group()
       omega_example.loc[tt,'Manufacturer/Brand']='Piaget'

In [ ]:
if BRND=='Longines':
   for tt in list(omega_example.index):
     for b in (omega_example.loc[tt,'Manufacturer/Brand']).split(' '):
        if b=='ETA':
          omega_example.loc[tt,'Manufacturer/Brand']='ETA'
if BRND=='Tudor':
   for tt in list(omega_example.index):
     for b in (omega_example.loc[tt,'Manufacturer/Brand']).split(' '):
        if b=='Kenissi':
          omega_example.loc[tt,'Manufacturer/Brand']='Kenissi'
if BRND=='Audemars Piguet':
   for tt in list(omega_example.index):
     for b in (omega_example.loc[tt,'Caliber Number']).split(','):
       if re.search('AP',b):     
         if re.search(r'\d+',b):
            omega_example.loc[tt,'Caliber Number']=re.search('AP',b).group()+re.search(r'\d+',b).group()
if BRND=='Tudor':
   for tt in list(omega_example.index):
     for b in (omega_example.loc[tt,'Caliber Number']).split(','):
       if re.search('MT',b):     
         if re.search(r'\d+',b):
            omega_example.loc[tt,'Caliber Number']=re.search('MT',b).group()+re.search(r'\d+',b).group()
if BRND=='Longines':
   for tt in list(omega_example.index):
     if re.search('ETA',omega_example.loc[tt,'Manufacturer/Brand']):
       if not re.search('ETA',omega_example.loc[tt,'Base caliber']):       
          omega_example.loc[tt,'Base caliber']='ETA '+omega_example.loc[tt,'Base caliber']
if BRND=='Longines':
   for tt in list(omega_example.index):
      if re.search('L836.6',omega_example.loc[tt,'Caliber Number']):
          omega_example.loc[tt,'Base caliber']='ETA C07.811'          
if BRND=='Longines':
   for tt in list(omega_example.index):
     if re.search('ETA',omega_example.loc[tt,'Base caliber']):
        omega_example.loc[tt,'Manufacturer/Brand']='Longines'
if BRND=='Tudor':
   for tt in list(omega_example.index):
     if re.search('Kenissi',omega_example.loc[tt,'Manufacturer/Brand']):
        omega_example.loc[tt,'Manufacturer/Brand']='Tudor'
        omega_example.loc[tt,'Base caliber']='Kenissi '+omega_example.loc[tt,'Caliber Number']
if BRND=='Tudor':
   for tt in list(omega_example.index):
     if re.search('T603',omega_example.loc[tt,'Caliber Number']):
        omega_example.loc[tt,'Base caliber']='Sellita SW240-1'
if BRND=='Longines':
    for tt in list(omega_example.index):
        if re.search('A31',omega_example.loc[tt,'Caliber Number']):
           omega_example.loc[tt,'Caliber Number']='L888'
           omega_example.loc[tt,'Base caliber']='ETA A31.L11'
if BRND=='Longines':
    for tt in list(omega_example.index):
        if re.search('L888',omega_example.loc[tt,'Caliber Number']):
           omega_example.loc[tt,'Base caliber']='ETA A31.L11'

In [ ]:
#final catalog
omega_example[omega_example.caliber_stories!=''].reset_index(drop=True).to_excel(f"{BRND.lower()}_cataloguev3.xlsx")

In [ ]:
omega_example.drop(['caliber_stories'],axis=1).to_excel(f"{BRND.lower()}_cataloguev4.xlsx")